name: Build SiksSevenMenu

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'  # или '9.x', '7.x', главное чтобы была поддержка net472

      - name: Build mod
        run: dotnet build SiksSevenMenu.csproj -c Release -p:Platform=x64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SiksSevenMenu.dll
          path: "**/bin/x64/Release/net472/SiksSevenMenu.dll"
